### PR TITLE
Add a "recommended" config to simplify usage

### PR DESCRIPTION
**Pull request by textbook**
Also make the Rules section of the README a table to track recommended/fixable status.

> **Meta**: When #11 and #12 are merged they should probably be added to the recommended rules as errors; if this PR is merged first I can update the others to use the rule table format and the recommended config.

### CODE REVIEW

**Comment by poenneby** [comment]
Hello @textbook - I am not sure how useful an "opinionated" configuration would be at this point. Perhaps when there are so many rules (see eslint) that you have no idea how to get a decent set configured. "Recommended" is also pretty subjective... Perhaps it would be more useful to have a "minimal" rule set (no rules switched on, just keywords) and a "strict" (all rules switched on) ?
Happy to be convinced otherwise 😄

**Comment by textbook** [comment]
I created the config primarily so you only add to add the plugin once, using `extends`, rather than needing both `plugins` _and_ `env` (which should maybe be `codeceptjs/globals`, going by other similar packages). My thinking was that "recommended" would turn on the rules that suggest a _mistake_ has been made (interfering with which tests are running can leave you thinking the suite is working when it actually isn't), but leave anything "to taste" out of it.

**Comment by poenneby** [comment]
Ok makes sense. I can see how everyone will go for the `recommended` configuration.
Personally I would recommend the `no-actor-in-scenario` rule to encourage using the page-object pattern and thus keeping the test suite maintainable. But perhaps that can be included in a future `strict` configuration.

**Comment by textbook** [comment]
I thought about that, but even [the docs](https://codecept.io/pageobjects/) show mixing actor and page object in their examples, and I definitely found that a useful pattern when writing tests, given the high-level selectors things like I.click give you.

**Comment by poenneby** [comment]
Ok @textbook I can see where you're coming from. The `recommended` config makes total sense now. While looking at this I came across another idea of providing an `all` config, the jest plugin does this in a [transparent way](https://github.com/jest-community/eslint-plugin-jest/blob/f41d5c4bcaa3fb15377df28f620db7c623635ac8/src/index.ts#L27). But let's get this merged now! 🙂

**Pull request merged**
