### PR TITLE
feat(async): allow async/await expressions

### PR DESCRIPTION
**Pull request by macintoshpie**
Update parsing to allow async functions and await expressions.

### CODE REVIEW

**Comment by poenneby** [comment]
Thanks @macintoshpie - looks good! However the test code is starting to get pretty complex - possible to simplify? Not sure we need to test all the valid function names, taking this out of the tests will remove some noise... Again sorry for taking so long to get back to you.

**Comment by poenneby** [comment]
Hello @macintoshpie - still interested in getting this feature merged?

**Comment by macintoshpie** [comment]
Hi, sorry for not getting back to ya. I haven't touched this in a while and the project I was on bailed on eslint, so I'll just close the pr.

**Comment by poenneby** [comment]
Hey thanks for getting back to me. I'm curious, bailed eslint for what? Prettier?

**Pull request closed without merging**
